// DINO WORLD animals (order = unlock order). Moved unchanged from DinosaurWorld.tsx (world template step 1).
import type { Animal } from "./types";

export const DINO_ANIMALS: Animal[] = [
  {
    id: "triceratops", name: "Triceratops", nameZh: "三角龍", emoji: "🦕",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/triceratop-egg.webp" },
      { name: "Baby", nameZh: "小三角龍", min: 15, img: "/creatures/triceratop-baby.webp" },
      { name: "Young", nameZh: "年輕三角龍", min: 30, img: "/creatures/triceratop-young.webp" },
      { name: "Grown", nameZh: "成年三角龍", min: 45, img: "/creatures/triceratop-grown.webp" },
    ],
    unlockCondition: "default",
    collectionBg: "#7c4a1a", collectionBorder: "rgba(218,165,32,0.7)", collectionGlow: "rgba(218,165,32,0.4)",
    video: "/video_adult_triceratop.mp4", isEggType: true, scale: 1,
    accentColor: "#DAA520", accentGlow: "rgba(218,165,32,0.5)",
    btnColor: "#b45309", btnGlow: "rgba(180,83,9,0.5)", btn3Color: "#556B2F", btn3Glow: "rgba(85,107,47,0.5)",
    feedLabel: "triceratops", feedLabelZh: "三角龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby Triceratops!", subZh: "快來認識你的小三角龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young Triceratops!", subZh: "現在是年輕三角龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown Triceratops!", subZh: "你養大了一隻成年三角龍！" },
    ],
    unlockOverlay: { emoji: "🦕", title: "Triceratops!", titleZh: "三角龍！", eggLine: "A Triceratops Egg appeared!", eggLineZh: "三角龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "Let's go! · 出發！🎉", glowColor: "rgba(218,165,32,0.6)", borderColor: "rgba(218,165,32,0.8)", bgGradient: "linear-gradient(135deg,#3d2b1f,#7c4a1a)" },
  },
  {
    id: "pterodactyl", name: "Pterodactyl", nameZh: "翼龍", emoji: "🦅",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/pterodactyl-egg.webp" },
      { name: "Baby", nameZh: "小翼龍", min: 15, img: "/creatures/pterodactyl-baby.webp" },
      { name: "Young", nameZh: "年輕翼龍", min: 30, img: "/creatures/pterodactyl-young.webp" },
      { name: "Grown", nameZh: "成年翼龍", min: 45, img: "/creatures/pterodactyl-grown.webp" },
    ],
    unlockCondition: "triceratops_grown_video_watched",
    collectionBg: "#5c3d11", collectionBorder: "rgba(210,105,30,0.7)", collectionGlow: "rgba(210,105,30,0.4)",
    video: "/video_adult_pterodactyl.mp4", isEggType: true, scale: 1.3,
    accentColor: "#D2691E", accentGlow: "rgba(210,105,30,0.5)",
    btnColor: "#D2691E", btnGlow: "rgba(210,105,30,0.5)", btn3Color: "#8B4513", btn3Glow: "rgba(139,69,19,0.5)",
    feedLabel: "pterodactyl", feedLabelZh: "翼龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby Pterodactyl!", subZh: "快來認識你的小翼龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young Pterodactyl!", subZh: "現在是年輕翼龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown Pterodactyl!", subZh: "你養大了一隻成年翼龍！" },
    ],
    unlockOverlay: { emoji: "🦅", title: "New Friend!", titleZh: "新朋友來了！", eggLine: "A Pterodactyl Egg appeared!", eggLineZh: "翼龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "So cool! · 太酷了！🎉", glowColor: "rgba(210,105,30,0.6)", borderColor: "rgba(210,105,30,0.8)", bgGradient: "linear-gradient(135deg,#2d1a08,#5c3d11,#8B4513)" },
  },
  {
    id: "velociraptor", name: "Velociraptor", nameZh: "迅猛龍", emoji: "🦖",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/velociraptor-egg.webp" },
      { name: "Baby", nameZh: "小迅猛龍", min: 15, img: "/creatures/velociraptor-baby.webp" },
      { name: "Young", nameZh: "年輕迅猛龍", min: 30, img: "/creatures/velociraptor-young.webp" },
      { name: "Grown", nameZh: "成年迅猛龍", min: 45, img: "/creatures/velociraptor-grown.webp" },
    ],
    unlockCondition: "pterodactyl_grown_video_watched",
    collectionBg: "#4a5c1a", collectionBorder: "rgba(107,142,35,0.7)", collectionGlow: "rgba(107,142,35,0.4)",
    video: "/video_adult_velociraptor.mp4", isEggType: true, scale: 1.2,
    accentColor: "#6B8E23", accentGlow: "rgba(107,142,35,0.5)",
    btnColor: "#556B2F", btnGlow: "rgba(85,107,47,0.5)", btn3Color: "#6B8E23", btn3Glow: "rgba(107,142,35,0.5)",
    feedLabel: "velociraptor", feedLabelZh: "迅猛龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby Velociraptor!", subZh: "快來認識你的小迅猛龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young Velociraptor!", subZh: "現在是年輕迅猛龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown Velociraptor!", subZh: "你養大了一隻成年迅猛龍！" },
    ],
    unlockOverlay: { emoji: "🦖", title: "New Friend!", titleZh: "新朋友來了！", eggLine: "A Velociraptor Egg appeared!", eggLineZh: "迅猛龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "So cool! · 太酷了！🎉", glowColor: "rgba(107,142,35,0.6)", borderColor: "rgba(107,142,35,0.8)", bgGradient: "linear-gradient(135deg,#1e2a08,#4a5c1a,#556B2F)" },
  },
  {
    id: "brontosaurus", name: "Brontosaurus", nameZh: "雷龍", emoji: "🦕",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/brontosaurus-egg.webp" },
      { name: "Baby", nameZh: "小雷龍", min: 15, img: "/creatures/brontosaurus-baby.webp" },
      { name: "Young", nameZh: "年輕雷龍", min: 30, img: "/creatures/brontosaurus-young.webp" },
      { name: "Grown", nameZh: "成年雷龍", min: 45, img: "/creatures/brontosaurus-grown.webp" },
    ],
    unlockCondition: "velociraptor_grown_video_watched",
    collectionBg: "#3d5c2a", collectionBorder: "rgba(154,205,50,0.7)", collectionGlow: "rgba(154,205,50,0.4)",
    video: "/video_adult_brontosaurus.mp4", isEggType: true, scale: 1.5,
    accentColor: "#9ACD32", accentGlow: "rgba(154,205,50,0.5)",
    btnColor: "#6B8E23", btnGlow: "rgba(107,142,35,0.5)", btn3Color: "#9ACD32", btn3Glow: "rgba(154,205,50,0.5)",
    feedLabel: "brontosaurus", feedLabelZh: "雷龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby Brontosaurus!", subZh: "快來認識你的小雷龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young Brontosaurus!", subZh: "現在是年輕雷龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown Brontosaurus!", subZh: "你養大了一隻成年雷龍！" },
    ],
    unlockOverlay: { emoji: "🦕", title: "New Friend!", titleZh: "新朋友來了！", eggLine: "A Brontosaurus Egg appeared!", eggLineZh: "雷龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "So cool! · 太酷了！🎉", glowColor: "rgba(154,205,50,0.6)", borderColor: "rgba(154,205,50,0.8)", bgGradient: "linear-gradient(135deg,#1a2e0d,#3d5c2a,#556B2F)" },
  },
  {
    id: "dilophosaurus", name: "Dilophosaurus", nameZh: "雙冠龍", emoji: "🦎",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/dilophosaurus-egg.webp" },
      { name: "Baby", nameZh: "小雙冠龍", min: 15, img: "/creatures/dilophosaurus-baby.webp" },
      { name: "Young", nameZh: "年輕雙冠龍", min: 30, img: "/creatures/dilophosaurus-young.webp" },
      { name: "Grown", nameZh: "成年雙冠龍", min: 45, img: "/creatures/dilophosaurus-grown.webp" },
    ],
    unlockCondition: "brontosaurus_grown_video_watched",
    collectionBg: "#7c2d12", collectionBorder: "rgba(234,88,12,0.7)", collectionGlow: "rgba(234,88,12,0.4)",
    video: "/video_adult_dilophosaurus.mp4", isEggType: true, scale: 1.2,
    accentColor: "#ea580c", accentGlow: "rgba(234,88,12,0.5)",
    btnColor: "#c2410c", btnGlow: "rgba(194,65,12,0.5)", btn3Color: "#ea580c", btn3Glow: "rgba(234,88,12,0.5)",
    feedLabel: "dilophosaurus", feedLabelZh: "雙冠龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby Dilophosaurus!", subZh: "快來認識你的小雙冠龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young Dilophosaurus!", subZh: "現在是年輕雙冠龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown Dilophosaurus!", subZh: "你養大了一隻成年雙冠龍！" },
    ],
    unlockOverlay: { emoji: "🦎", title: "New Friend!", titleZh: "新朋友來了！", eggLine: "A Dilophosaurus Egg appeared!", eggLineZh: "雙冠龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "So cool! · 太酷了！🎉", glowColor: "rgba(234,88,12,0.6)", borderColor: "rgba(234,88,12,0.8)", bgGradient: "linear-gradient(135deg,#3d0f04,#7c2d12,#c2410c)" },
  },
  {
    id: "trex", name: "T-Rex", nameZh: "暴龍", emoji: "🦖",
    stages: [
      { name: "Egg", nameZh: "蛋", min: 0, img: "/creatures/trex-egg.webp" },
      { name: "Baby", nameZh: "小暴龍", min: 15, img: "/creatures/trex-baby.webp" },
      { name: "Young", nameZh: "年輕暴龍", min: 30, img: "/creatures/trex-young.webp" },
      { name: "Grown", nameZh: "成年暴龍", min: 45, img: "/creatures/trex-grown.webp" },
    ],
    unlockCondition: "dilophosaurus_grown_video_watched",
    collectionBg: "#6b1a1a", collectionBorder: "rgba(220,38,38,0.7)", collectionGlow: "rgba(220,38,38,0.4)",
    video: "/video_adult_trex.mp4", isEggType: true, scale: 1.6,
    accentColor: "#dc2626", accentGlow: "rgba(220,38,38,0.5)",
    btnColor: "#b91c1c", btnGlow: "rgba(185,28,28,0.5)", btn3Color: "#dc2626", btn3Glow: "rgba(220,38,38,0.5)",
    feedLabel: "t-rex", feedLabelZh: "暴龍",
    levelUpMessages: [
      { main: "Welcome, little one!", zh: "歡迎來到恐龍世界！", sub: "Meet your Baby T-Rex!", subZh: "快來認識你的小暴龍！" },
      { main: "Growing strong!", zh: "長得好壯！", sub: "Now a Young T-Rex!", subZh: "現在是年輕暴龍了！" },
      { main: "Fully grown! ROAR!", zh: "完全長大了！吼！", sub: "You raised a Grown T-Rex!", subZh: "你養大了一隻成年暴龍！" },
    ],
    unlockOverlay: { emoji: "🦖", title: "T-REX!", titleZh: "暴龍！", eggLine: "A T-Rex Egg appeared!", eggLineZh: "暴龍蛋出現了！", feedLine: "Feed it treats to help it grow!", feedLineZh: "餵他點心讓他長大！", btnText: "ROAR! · 吼！🦖", glowColor: "rgba(220,38,38,0.6)", borderColor: "rgba(220,38,38,0.8)", bgGradient: "linear-gradient(135deg,#2d0808,#6b1a1a,#b91c1c)" },
  },
];
