#!/usr/bin/env python3
"""Rebuild the inline grammar sentence pools inside the 4 grammar game HTML files.

Source of truth: src/data/grammar-<game>-level<N>.json   (game = swim | run | dig | grab)
Run from the project root:   python3 scripts/build-grammar-pools.py
Dry run (check only):        python3 scripts/build-grammar-pools.py --check

Only the text between the @@GRAMMAR_POOLS markers in each game is replaced.
Every JSON file is validated first; if ANY file is wrong, NOTHING is written.
Levels with no JSON file fall back to Level 1 inside the game.
"""
import glob, json, os, re, sys

GAMES = {  # game: (html file, variable the rest of the game already uses)
    "swim": ("public/Teacher_Andy_Swim_game.html", "SWIM_POOL"),
    "run":  ("public/Teacher_Andy_Run_game.html",  "RUN_POOL"),
    "dig":  ("public/Teacher_Andy_Dig_game.html",  "DIG_POOL"),
    "grab": ("public/Teacher_Andy_Grab_game.html", "RAW_SENTENCES"),
}
START = "/*@@GRAMMAR_POOLS_START (generated by scripts/build-grammar-pools.py - do not hand-edit)*/"
END = "/*@@GRAMMAR_POOLS_END*/"
TOKENS = re.compile(r"[A-Za-z']+|[.?!,]")   # Dig: "I have a cat." -> ["I","have","a","cat","."]


def problems(game, item):
    """Return a list of what's wrong with one item (empty list = OK)."""
    p = []
    if game == "swim":
        if not (isinstance(item, dict) and isinstance(item.get("s"), str) and isinstance(item.get("ans"), bool)):
            p.append("needs {s: text, ans: true/false}")
    elif game == "run":
        if not (isinstance(item, dict) and isinstance(item.get("before"), str) and isinstance(item.get("after"), str)
                and isinstance(item.get("answers"), list) and len(item["answers"]) == 3
                and isinstance(item.get("correct"), int) and 0 <= item["correct"] < 3):
            p.append("needs {before, after, answers: [3 words], correct: 0-2}")
    elif game == "dig":
        if not (isinstance(item, str) and TOKENS.findall(item) and "".join(TOKENS.findall(item)) == re.sub(r"\s", "", item)
                and item.strip()[-1:] in ".?!"):
            p.append("needs a plain sentence of letters and . ? ! , only, ending in . ? or !")
    elif game == "grab":
        if not (isinstance(item, dict) and isinstance(item.get("text"), str) and item["text"].count("___") == 1
                and isinstance(item.get("options"), list) and len(item["options"]) == 2
                and item.get("correct") in item["options"] and len(set(item["options"])) == 2):
            p.append("needs {text with one ___, correct, options: [2 different words incl. correct]}")
    return p


def load_pools(game):
    pools, errors = {}, []
    for f in glob.glob(f"src/data/grammar-{game}-level*.json"):
        m = re.search(r"level(\d+)\.json$", f)
        if not m:
            continue
        n = int(m.group(1))
        try:
            data = json.load(open(f, encoding="utf-8"))
        except Exception as e:
            errors.append(f"{f}: not valid JSON ({e})"); continue
        if not isinstance(data, list) or not data:
            errors.append(f"{f}: must be a non-empty list"); continue
        for i, item in enumerate(data):
            for p in problems(game, item):
                errors.append(f"{f} item {i + 1}: {p} -> {str(item)[:80]}")
        if game == "dig":
            data = [TOKENS.findall(s) if isinstance(s, str) else s for s in data]
        pools[n] = data
    if 1 not in pools:
        errors.append(f"{game}: no level 1 file (src/data/grammar-{game}-level1.json)")
    return {str(k): pools[k] for k in sorted(pools)}, errors


def block(var, pools):
    return (START + "\n"
            + f"const {var}_POOLS=" + json.dumps(pools, ensure_ascii=False) + ";\n"
            + "const LEVEL=(new URLSearchParams(location.search).get('level'))||'1';\n"
            + f"const {var}={var}_POOLS[LEVEL]||{var}_POOLS[\"1\"];\n"
            + END)


def main():
    check_only = "--check" in sys.argv
    new_texts, errors, report = {}, [], []
    for game, (html, var) in GAMES.items():
        pools, errs = load_pools(game)
        errors += errs
        try:
            text = open(html, encoding="utf-8").read()
        except FileNotFoundError:
            errors.append(f"{html}: missing"); continue
        if text.count(START) != 1 or text.count(END) != 1:
            errors.append(f"{html}: needs exactly one START and one END marker")
            continue
        a = text.index(START); b = text.index(END) + len(END)
        new = text[:a] + block(var, pools) + text[b:]
        new_texts[html] = new
        report.append(f"{game}: levels {', '.join(pools) or '-'} ({', '.join(str(len(v)) for v in pools.values())} items)"
                      + ("" if new != text else "  [no change]"))
    if errors:
        print("ABORT - nothing written. Fix these:")
        for e in errors:
            print("  -", e)
        sys.exit(1)
    print("\n".join(report))
    if check_only:
        print("--check: all files OK, nothing written."); return
    for html, new in new_texts.items():
        with open(html + ".tmp", "w", encoding="utf-8") as fh:
            fh.write(new)
        os.replace(html + ".tmp", html)
    print("WRITTEN")


if __name__ == "__main__":
    main()
